### ISSUE TITLE
New Release Request

### ISSUE THREAD

**Issue by itsthejoker** [AlexAltea/milli-py#6]
Hi, Alex! I created a [Django wrapper](https://github.com/itsthejoker/django-milli) for `milli-py` for one of my projects, but I can't put it on pypi untila new release for `milli-py` is created due to PyPI not allowing projects to link to github repos for dependencies. Would it be possible to get a new release so I can publish my wrapper? I would like to do a small presentation on it at PyCon this year, which is about a week away.

Thanks!

**Comment by AlexAltea** [comment]
@itsthejoker Apologies, I was on holidays the entire week. I'll take care of this ASAP.

**Comment by itsthejoker** [comment]
Not an issue -- holidays are important!! I'm on vacation too lol. Thank you very much,!

**Comment by AlexAltea** [comment]
Done! See https://github.com/AlexAltea/milli-py/issues/4#issuecomment-1512799944
